//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for calculated_metric_type_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="calculated_metric_type_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="numeric"/>
 *     &lt;enumeration value="percent"/>
 *     &lt;enumeration value="currency"/>
 *     &lt;enumeration value="time"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "calculated_metric_type_enum")
@XmlEnum
public enum CalculatedMetricTypeEnum {

    @XmlEnumValue("numeric")
    NUMERIC("numeric"),
    @XmlEnumValue("percent")
    PERCENT("percent"),
    @XmlEnumValue("currency")
    CURRENCY("currency"),
    @XmlEnumValue("time")
    TIME("time");
    private final String value;

    CalculatedMetricTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CalculatedMetricTypeEnum fromValue(String v) {
        for (CalculatedMetricTypeEnum c: CalculatedMetricTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
