//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classification_type_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="classification_type_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="text"/>
 *     &lt;enumeration value="numeric"/>
 *     &lt;enumeration value="numeric_percent"/>
 *     &lt;enumeration value="numeric_currency"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "classification_type_enum")
@XmlEnum
public enum ClassificationTypeEnum {

    @XmlEnumValue("text")
    TEXT("text"),
    @XmlEnumValue("numeric")
    NUMERIC("numeric"),
    @XmlEnumValue("numeric_percent")
    NUMERIC_PERCENT("numeric_percent"),
    @XmlEnumValue("numeric_currency")
    NUMERIC_CURRENCY("numeric_currency");
    private final String value;

    ClassificationTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClassificationTypeEnum fromValue(String v) {
        for (ClassificationTypeEnum c: ClassificationTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
