//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dashboard_display_info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dashboard_display_info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="row" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="col" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="rowspan" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="colspan" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="graph" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="table" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="maxRows" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dashboard_display_info", propOrder = {

})
public class DashboardDisplayInfo {

    protected int row;
    protected int col;
    protected int rowspan;
    protected int colspan;
    protected boolean graph;
    protected boolean summary;
    protected boolean table;
    protected int maxRows;
    @XmlElement(required = true)
    protected String note;

    /**
     * Gets the value of the row property.
     * 
     */
    public int getRow() {
        return row;
    }

    /**
     * Sets the value of the row property.
     * 
     */
    public void setRow(int value) {
        this.row = value;
    }

    /**
     * Gets the value of the col property.
     * 
     */
    public int getCol() {
        return col;
    }

    /**
     * Sets the value of the col property.
     * 
     */
    public void setCol(int value) {
        this.col = value;
    }

    /**
     * Gets the value of the rowspan property.
     * 
     */
    public int getRowspan() {
        return rowspan;
    }

    /**
     * Sets the value of the rowspan property.
     * 
     */
    public void setRowspan(int value) {
        this.rowspan = value;
    }

    /**
     * Gets the value of the colspan property.
     * 
     */
    public int getColspan() {
        return colspan;
    }

    /**
     * Sets the value of the colspan property.
     * 
     */
    public void setColspan(int value) {
        this.colspan = value;
    }

    /**
     * Gets the value of the graph property.
     * 
     */
    public boolean isGraph() {
        return graph;
    }

    /**
     * Sets the value of the graph property.
     * 
     */
    public void setGraph(boolean value) {
        this.graph = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     */
    public boolean isSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     */
    public void setSummary(boolean value) {
        this.summary = value;
    }

    /**
     * Gets the value of the table property.
     * 
     */
    public boolean isTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     */
    public void setTable(boolean value) {
        this.table = value;
    }

    /**
     * Gets the value of the maxRows property.
     * 
     */
    public int getMaxRows() {
        return maxRows;
    }

    /**
     * Sets the value of the maxRows property.
     * 
     */
    public void setMaxRows(int value) {
        this.maxRows = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

}
