//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for data_warehouse_display_type_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="data_warehouse_display_type_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="all-logins-have-access"/>
 *     &lt;enumeration value="grayed-out-tab"/>
 *     &lt;enumeration value="admins-only"/>
 *     &lt;enumeration value="disabled"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "data_warehouse_display_type_enum")
@XmlEnum
public enum DataWarehouseDisplayTypeEnum {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("all-logins-have-access")
    ALL_LOGINS_HAVE_ACCESS("all-logins-have-access"),
    @XmlEnumValue("grayed-out-tab")
    GRAYED_OUT_TAB("grayed-out-tab"),
    @XmlEnumValue("admins-only")
    ADMINS_ONLY("admins-only"),
    @XmlEnumValue("disabled")
    DISABLED("disabled");
    private final String value;

    DataWarehouseDisplayTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataWarehouseDisplayTypeEnum fromValue(String v) {
        for (DataWarehouseDisplayTypeEnum c: DataWarehouseDisplayTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
