//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for data_source_weblog_formats.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="data_source_weblog_formats">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ncsa_common"/>
 *     &lt;enumeration value="ncsa_combined"/>
 *     &lt;enumeration value="w3c_extended"/>
 *     &lt;enumeration value="microsoft_iis"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "data_source_weblog_formats")
@XmlEnum
public enum DataSourceWeblogFormats {

    @XmlEnumValue("ncsa_common")
    NCSA_COMMON("ncsa_common"),
    @XmlEnumValue("ncsa_combined")
    NCSA_COMBINED("ncsa_combined"),
    @XmlEnumValue("w3c_extended")
    W_3_C_EXTENDED("w3c_extended"),
    @XmlEnumValue("microsoft_iis")
    MICROSOFT_IIS("microsoft_iis");
    private final String value;

    DataSourceWeblogFormats(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataSourceWeblogFormats fromValue(String v) {
        for (DataSourceWeblogFormats c: DataSourceWeblogFormats.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
