//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://marketing.adobe.com/analytics/2015/04/16}event_type_enum"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="default_metric" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="participation" type="{http://marketing.adobe.com/analytics/2015/04/16}event_participation_enum"/>
 *         &lt;element name="serialization" type="{http://marketing.adobe.com/analytics/2015/04/16}event_serialization_enum"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "event", propOrder = {

})
public class Event {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true, nillable = true)
    protected String name;
    @XmlElement(required = true, nillable = true)
    protected EventTypeEnum type;
    @XmlElement(required = true, nillable = true)
    protected String description;
    @XmlElement(name = "default_metric", required = true, type = Boolean.class, nillable = true)
    protected Boolean defaultMetric;
    @XmlElement(required = true, nillable = true)
    protected EventParticipationEnum participation;
    @XmlElement(required = true, nillable = true)
    protected EventSerializationEnum serialization;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EventTypeEnum }
     *     
     */
    public EventTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventTypeEnum }
     *     
     */
    public void setType(EventTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the defaultMetric property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefaultMetric() {
        return defaultMetric;
    }

    /**
     * Sets the value of the defaultMetric property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefaultMetric(Boolean value) {
        this.defaultMetric = value;
    }

    /**
     * Gets the value of the participation property.
     * 
     * @return
     *     possible object is
     *     {@link EventParticipationEnum }
     *     
     */
    public EventParticipationEnum getParticipation() {
        return participation;
    }

    /**
     * Sets the value of the participation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventParticipationEnum }
     *     
     */
    public void setParticipation(EventParticipationEnum value) {
        this.participation = value;
    }

    /**
     * Gets the value of the serialization property.
     * 
     * @return
     *     possible object is
     *     {@link EventSerializationEnum }
     *     
     */
    public EventSerializationEnum getSerialization() {
        return serialization;
    }

    /**
     * Sets the value of the serialization property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSerializationEnum }
     *     
     */
    public void setSerialization(EventSerializationEnum value) {
        this.serialization = value;
    }

}
