//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for event_serialization_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="event_serialization_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="unavailable"/>
 *     &lt;enumeration value="always_record"/>
 *     &lt;enumeration value="record_once_per_visit"/>
 *     &lt;enumeration value="record_once_per_unique_id"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "event_serialization_enum")
@XmlEnum
public enum EventSerializationEnum {

    @XmlEnumValue("unavailable")
    UNAVAILABLE("unavailable"),
    @XmlEnumValue("always_record")
    ALWAYS_RECORD("always_record"),
    @XmlEnumValue("record_once_per_visit")
    RECORD_ONCE_PER_VISIT("record_once_per_visit"),
    @XmlEnumValue("record_once_per_unique_id")
    RECORD_ONCE_PER_UNIQUE_ID("record_once_per_unique_id");
    private final String value;

    EventSerializationEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventSerializationEnum fromValue(String v) {
        for (EventSerializationEnum c: EventSerializationEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
