//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hit_attribute_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="hit_attribute_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="campaign"/>
 *     &lt;enumeration value="evar"/>
 *     &lt;enumeration value="external_referring_domain"/>
 *     &lt;enumeration value="external_referring_url"/>
 *     &lt;enumeration value="external_referring_qs_param"/>
 *     &lt;enumeration value="page"/>
 *     &lt;enumeration value="page_url"/>
 *     &lt;enumeration value="page_qs_param"/>
 *     &lt;enumeration value="is_paid_search"/>
 *     &lt;enumeration value="is_natural_search"/>
 *     &lt;enumeration value="search_engine"/>
 *     &lt;enumeration value="search_keywords"/>
 *     &lt;enumeration value="search_tracking_code"/>
 *     &lt;enumeration value="is_internal"/>
 *     &lt;enumeration value="is_first_page_of_visit"/>
 *     &lt;enumeration value="is_search_center"/>
 *     &lt;enumeration value="external_referring_root_domain"/>
 *     &lt;enumeration value="external_referring_domain_and_path"/>
 *     &lt;enumeration value="page_domain"/>
 *     &lt;enumeration value="page_root_domain"/>
 *     &lt;enumeration value="page_domain_and_path"/>
 *     &lt;enumeration value="is_not_internal"/>
 *     &lt;enumeration value="internal_referring_url"/>
 *     &lt;enumeration value="internal_referring_qs_param"/>
 *     &lt;enumeration value="internal_referring_domain"/>
 *     &lt;enumeration value="internal_referring_root_domain"/>
 *     &lt;enumeration value="internal_referring_domain_and_path"/>
 *     &lt;enumeration value="referring_url"/>
 *     &lt;enumeration value="referring_qs_param"/>
 *     &lt;enumeration value="referring_domain"/>
 *     &lt;enumeration value="referring_root_domain"/>
 *     &lt;enumeration value="referring_domain_and_path"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "hit_attribute_type")
@XmlEnum
public enum HitAttributeType {

    @XmlEnumValue("campaign")
    CAMPAIGN("campaign"),
    @XmlEnumValue("evar")
    EVAR("evar"),
    @XmlEnumValue("external_referring_domain")
    EXTERNAL_REFERRING_DOMAIN("external_referring_domain"),
    @XmlEnumValue("external_referring_url")
    EXTERNAL_REFERRING_URL("external_referring_url"),
    @XmlEnumValue("external_referring_qs_param")
    EXTERNAL_REFERRING_QS_PARAM("external_referring_qs_param"),
    @XmlEnumValue("page")
    PAGE("page"),
    @XmlEnumValue("page_url")
    PAGE_URL("page_url"),
    @XmlEnumValue("page_qs_param")
    PAGE_QS_PARAM("page_qs_param"),
    @XmlEnumValue("is_paid_search")
    IS_PAID_SEARCH("is_paid_search"),
    @XmlEnumValue("is_natural_search")
    IS_NATURAL_SEARCH("is_natural_search"),
    @XmlEnumValue("search_engine")
    SEARCH_ENGINE("search_engine"),
    @XmlEnumValue("search_keywords")
    SEARCH_KEYWORDS("search_keywords"),
    @XmlEnumValue("search_tracking_code")
    SEARCH_TRACKING_CODE("search_tracking_code"),
    @XmlEnumValue("is_internal")
    IS_INTERNAL("is_internal"),
    @XmlEnumValue("is_first_page_of_visit")
    IS_FIRST_PAGE_OF_VISIT("is_first_page_of_visit"),
    @XmlEnumValue("is_search_center")
    IS_SEARCH_CENTER("is_search_center"),
    @XmlEnumValue("external_referring_root_domain")
    EXTERNAL_REFERRING_ROOT_DOMAIN("external_referring_root_domain"),
    @XmlEnumValue("external_referring_domain_and_path")
    EXTERNAL_REFERRING_DOMAIN_AND_PATH("external_referring_domain_and_path"),
    @XmlEnumValue("page_domain")
    PAGE_DOMAIN("page_domain"),
    @XmlEnumValue("page_root_domain")
    PAGE_ROOT_DOMAIN("page_root_domain"),
    @XmlEnumValue("page_domain_and_path")
    PAGE_DOMAIN_AND_PATH("page_domain_and_path"),
    @XmlEnumValue("is_not_internal")
    IS_NOT_INTERNAL("is_not_internal"),
    @XmlEnumValue("internal_referring_url")
    INTERNAL_REFERRING_URL("internal_referring_url"),
    @XmlEnumValue("internal_referring_qs_param")
    INTERNAL_REFERRING_QS_PARAM("internal_referring_qs_param"),
    @XmlEnumValue("internal_referring_domain")
    INTERNAL_REFERRING_DOMAIN("internal_referring_domain"),
    @XmlEnumValue("internal_referring_root_domain")
    INTERNAL_REFERRING_ROOT_DOMAIN("internal_referring_root_domain"),
    @XmlEnumValue("internal_referring_domain_and_path")
    INTERNAL_REFERRING_DOMAIN_AND_PATH("internal_referring_domain_and_path"),
    @XmlEnumValue("referring_url")
    REFERRING_URL("referring_url"),
    @XmlEnumValue("referring_qs_param")
    REFERRING_QS_PARAM("referring_qs_param"),
    @XmlEnumValue("referring_domain")
    REFERRING_DOMAIN("referring_domain"),
    @XmlEnumValue("referring_root_domain")
    REFERRING_ROOT_DOMAIN("referring_root_domain"),
    @XmlEnumValue("referring_domain_and_path")
    REFERRING_DOMAIN_AND_PATH("referring_domain_and_path");
    private final String value;

    HitAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HitAttributeType fromValue(String v) {
        for (HitAttributeType c: HitAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
