//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ip_obfuscation_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ip_obfuscation_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="obfuscated"/>
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="ip_removed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ip_obfuscation_enum")
@XmlEnum
public enum IpObfuscationEnum {

    @XmlEnumValue("obfuscated")
    OBFUSCATED("obfuscated"),
    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("ip_removed")
    IP_REMOVED("ip_removed");
    private final String value;

    IpObfuscationEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IpObfuscationEnum fromValue(String v) {
        for (IpObfuscationEnum c: IpObfuscationEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
