//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for list_variable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="list_variable">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="allocation_type" type="{http://marketing.adobe.com/analytics/2015/04/16}list_variable_allocation_type"/>
 *         &lt;element name="expiration_type" type="{http://marketing.adobe.com/analytics/2015/04/16}list_variable_expiration_type"/>
 *         &lt;element name="expiration_custom_days" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="value_delimiter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="max_values" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "list_variable", propOrder = {

})
public class ListVariable {

    protected int id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "allocation_type", required = true)
    protected ListVariableAllocationType allocationType;
    @XmlElement(name = "expiration_type", required = true)
    protected ListVariableExpirationType expirationType;
    @XmlElement(name = "expiration_custom_days")
    protected int expirationCustomDays;
    @XmlElement(name = "value_delimiter", required = true)
    protected String valueDelimiter;
    @XmlElement(name = "max_values", required = true)
    protected String maxValues;
    protected int enabled;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the allocationType property.
     * 
     * @return
     *     possible object is
     *     {@link ListVariableAllocationType }
     *     
     */
    public ListVariableAllocationType getAllocationType() {
        return allocationType;
    }

    /**
     * Sets the value of the allocationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListVariableAllocationType }
     *     
     */
    public void setAllocationType(ListVariableAllocationType value) {
        this.allocationType = value;
    }

    /**
     * Gets the value of the expirationType property.
     * 
     * @return
     *     possible object is
     *     {@link ListVariableExpirationType }
     *     
     */
    public ListVariableExpirationType getExpirationType() {
        return expirationType;
    }

    /**
     * Sets the value of the expirationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListVariableExpirationType }
     *     
     */
    public void setExpirationType(ListVariableExpirationType value) {
        this.expirationType = value;
    }

    /**
     * Gets the value of the expirationCustomDays property.
     * 
     */
    public int getExpirationCustomDays() {
        return expirationCustomDays;
    }

    /**
     * Sets the value of the expirationCustomDays property.
     * 
     */
    public void setExpirationCustomDays(int value) {
        this.expirationCustomDays = value;
    }

    /**
     * Gets the value of the valueDelimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDelimiter() {
        return valueDelimiter;
    }

    /**
     * Sets the value of the valueDelimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDelimiter(String value) {
        this.valueDelimiter = value;
    }

    /**
     * Gets the value of the maxValues property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxValues() {
        return maxValues;
    }

    /**
     * Sets the value of the maxValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxValues(String value) {
        this.maxValues = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public int getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(int value) {
        this.enabled = value;
    }

}
