//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for marketing_channel_rule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="marketing_channel_rule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="rule_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="hit_attribute" type="{http://marketing.adobe.com/analytics/2015/04/16}hit_attribute"/>
 *         &lt;element name="operator" type="{http://marketing.adobe.com/analytics/2015/04/16}ruleset_operator_type"/>
 *         &lt;element name="matches" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "marketing_channel_rule", propOrder = {

})
public class MarketingChannelRule {

    @XmlElement(name = "rule_id")
    protected int ruleId;
    @XmlElement(name = "hit_attribute", required = true)
    protected HitAttribute hitAttribute;
    @XmlElement(required = true)
    protected RulesetOperatorType operator;
    @XmlElement(required = true)
    protected List<String> matches;

    /**
     * Gets the value of the ruleId property.
     * 
     */
    public int getRuleId() {
        return ruleId;
    }

    /**
     * Sets the value of the ruleId property.
     * 
     */
    public void setRuleId(int value) {
        this.ruleId = value;
    }

    /**
     * Gets the value of the hitAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link HitAttribute }
     *     
     */
    public HitAttribute getHitAttribute() {
        return hitAttribute;
    }

    /**
     * Sets the value of the hitAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitAttribute }
     *     
     */
    public void setHitAttribute(HitAttribute value) {
        this.hitAttribute = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link RulesetOperatorType }
     *     
     */
    public RulesetOperatorType getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesetOperatorType }
     *     
     */
    public void setOperator(RulesetOperatorType value) {
        this.operator = value;
    }

    /**
     * Gets the value of the matches property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the matches property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatches().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMatches() {
        if (matches == null) {
            matches = new ArrayList<String>();
        }
        return this.matches;
    }

}
