//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for marketing_channel_ruleset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="marketing_channel_ruleset">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ruleset_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="channel_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="junction" type="{http://marketing.adobe.com/analytics/2015/04/16}ruleset_junction_type"/>
 *         &lt;element name="channel_value" type="{http://marketing.adobe.com/analytics/2015/04/16}channel_value_attribute"/>
 *         &lt;element name="rules" type="{http://marketing.adobe.com/analytics/2015/04/16}marketing_channel_rule" maxOccurs="unbounded"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "marketing_channel_ruleset", propOrder = {

})
public class MarketingChannelRuleset {

    @XmlElement(name = "ruleset_id")
    protected int rulesetId;
    @XmlElement(name = "channel_id")
    protected int channelId;
    @XmlElement(required = true)
    protected RulesetJunctionType junction;
    @XmlElement(name = "channel_value", required = true)
    protected ChannelValueAttribute channelValue;
    @XmlElement(required = true)
    protected List<MarketingChannelRule> rules;

    /**
     * Gets the value of the rulesetId property.
     * 
     */
    public int getRulesetId() {
        return rulesetId;
    }

    /**
     * Sets the value of the rulesetId property.
     * 
     */
    public void setRulesetId(int value) {
        this.rulesetId = value;
    }

    /**
     * Gets the value of the channelId property.
     * 
     */
    public int getChannelId() {
        return channelId;
    }

    /**
     * Sets the value of the channelId property.
     * 
     */
    public void setChannelId(int value) {
        this.channelId = value;
    }

    /**
     * Gets the value of the junction property.
     * 
     * @return
     *     possible object is
     *     {@link RulesetJunctionType }
     *     
     */
    public RulesetJunctionType getJunction() {
        return junction;
    }

    /**
     * Sets the value of the junction property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesetJunctionType }
     *     
     */
    public void setJunction(RulesetJunctionType value) {
        this.junction = value;
    }

    /**
     * Gets the value of the channelValue property.
     * 
     * @return
     *     possible object is
     *     {@link ChannelValueAttribute }
     *     
     */
    public ChannelValueAttribute getChannelValue() {
        return channelValue;
    }

    /**
     * Sets the value of the channelValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChannelValueAttribute }
     *     
     */
    public void setChannelValue(ChannelValueAttribute value) {
        this.channelValue = value;
    }

    /**
     * Gets the value of the rules property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rules property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRules().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarketingChannelRule }
     * 
     * 
     */
    public List<MarketingChannelRule> getRules() {
        if (rules == null) {
            rules = new ArrayList<MarketingChannelRule>();
        }
        return this.rules;
    }

}
