//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.adobe.analytics.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.adobe.analytics.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DashboardReturn }
     * 
     */
    public DashboardReturn createDashboardReturn() {
        return new DashboardReturn();
    }

    /**
     * Create an instance of {@link CalculatedMetric }
     * 
     */
    public CalculatedMetric createCalculatedMetric() {
        return new CalculatedMetric();
    }

    /**
     * Create an instance of {@link ReportSuiteBaseCurrency }
     * 
     */
    public ReportSuiteBaseCurrency createReportSuiteBaseCurrency() {
        return new ReportSuiteBaseCurrency();
    }

    /**
     * Create an instance of {@link ReportSuitePermanentTraffic }
     * 
     */
    public ReportSuitePermanentTraffic createReportSuitePermanentTraffic() {
        return new ReportSuitePermanentTraffic();
    }

    /**
     * Create an instance of {@link MarketingChannel }
     * 
     */
    public MarketingChannel createMarketingChannel() {
        return new MarketingChannel();
    }

    /**
     * Create an instance of {@link SegmentItem }
     * 
     */
    public SegmentItem createSegmentItem() {
        return new SegmentItem();
    }

    /**
     * Create an instance of {@link ClassificationsReportSuiteTemplate }
     * 
     */
    public ClassificationsReportSuiteTemplate createClassificationsReportSuiteTemplate() {
        return new ClassificationsReportSuiteTemplate();
    }

    /**
     * Create an instance of {@link ClassificationsReportSuiteFtp }
     * 
     */
    public ClassificationsReportSuiteFtp createClassificationsReportSuiteFtp() {
        return new ClassificationsReportSuiteFtp();
    }

    /**
     * Create an instance of {@link ReportMetric }
     * 
     */
    public ReportMetric createReportMetric() {
        return new ReportMetric();
    }

    /**
     * Create an instance of {@link DataFeed }
     * 
     */
    public DataFeed createDataFeed() {
        return new DataFeed();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link ReportReportSuite }
     * 
     */
    public ReportReportSuite createReportReportSuite() {
        return new ReportReportSuite();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link ReportSuiteCalculatedMetrics }
     * 
     */
    public ReportSuiteCalculatedMetrics createReportSuiteCalculatedMetrics() {
        return new ReportSuiteCalculatedMetrics();
    }

    /**
     * Create an instance of {@link Evar }
     * 
     */
    public Evar createEvar() {
        return new Evar();
    }

    /**
     * Create an instance of {@link ReportSuiteEcommerce }
     * 
     */
    public ReportSuiteEcommerce createReportSuiteEcommerce() {
        return new ReportSuiteEcommerce();
    }

    /**
     * Create an instance of {@link ClassificationsReportSuiteCompatibilityElements }
     * 
     */
    public ClassificationsReportSuiteCompatibilityElements createClassificationsReportSuiteCompatibilityElements() {
        return new ClassificationsReportSuiteCompatibilityElements();
    }

    /**
     * Create an instance of {@link ReportSuitePaidSearchDetection }
     * 
     */
    public ReportSuitePaidSearchDetection createReportSuitePaidSearchDetection() {
        return new ReportSuitePaidSearchDetection();
    }

    /**
     * Create an instance of {@link Pagedetail }
     * 
     */
    public Pagedetail createPagedetail() {
        return new Pagedetail();
    }

    /**
     * Create an instance of {@link Bookmark }
     * 
     */
    public Bookmark createBookmark() {
        return new Bookmark();
    }

    /**
     * Create an instance of {@link ReportSuiteGeoSegmentation }
     * 
     */
    public ReportSuiteGeoSegmentation createReportSuiteGeoSegmentation() {
        return new ReportSuiteGeoSegmentation();
    }

    /**
     * Create an instance of {@link MarketingChannelRule }
     * 
     */
    public MarketingChannelRule createMarketingChannelRule() {
        return new MarketingChannelRule();
    }

    /**
     * Create an instance of {@link DeleteCalculatedMetric }
     * 
     */
    public DeleteCalculatedMetric createDeleteCalculatedMetric() {
        return new DeleteCalculatedMetric();
    }

    /**
     * Create an instance of {@link ExcelWorkbook }
     * 
     */
    public ExcelWorkbook createExcelWorkbook() {
        return new ExcelWorkbook();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link ReportDescriptionSegmentSearch }
     * 
     */
    public ReportDescriptionSegmentSearch createReportDescriptionSegmentSearch() {
        return new ReportDescriptionSegmentSearch();
    }

    /**
     * Create an instance of {@link ReportSuiteInternalUrlFilters }
     * 
     */
    public ReportSuiteInternalUrlFilters createReportSuiteInternalUrlFilters() {
        return new ReportSuiteInternalUrlFilters();
    }

    /**
     * Create an instance of {@link ReportSuiteScheduledSpike }
     * 
     */
    public ReportSuiteScheduledSpike createReportSuiteScheduledSpike() {
        return new ReportSuiteScheduledSpike();
    }

    /**
     * Create an instance of {@link ReportAccess }
     * 
     */
    public ReportAccess createReportAccess() {
        return new ReportAccess();
    }

    /**
     * Create an instance of {@link Dashboard }
     * 
     */
    public Dashboard createDashboard() {
        return new Dashboard();
    }

    /**
     * Create an instance of {@link ReportSuiteDefaultPage }
     * 
     */
    public ReportSuiteDefaultPage createReportSuiteDefaultPage() {
        return new ReportSuiteDefaultPage();
    }

    /**
     * Create an instance of {@link ReportSuiteVideoSettings }
     * 
     */
    public ReportSuiteVideoSettings createReportSuiteVideoSettings() {
        return new ReportSuiteVideoSettings();
    }

    /**
     * Create an instance of {@link ReportResponse }
     * 
     */
    public ReportResponse createReportResponse() {
        return new ReportResponse();
    }

    /**
     * Create an instance of {@link ReportSuiteElementClassifications }
     * 
     */
    public ReportSuiteElementClassifications createReportSuiteElementClassifications() {
        return new ReportSuiteElementClassifications();
    }

    /**
     * Create an instance of {@link ReportSuiteMarketingChannelCosts }
     * 
     */
    public ReportSuiteMarketingChannelCosts createReportSuiteMarketingChannelCosts() {
        return new ReportSuiteMarketingChannelCosts();
    }

    /**
     * Create an instance of {@link PermissionGroupSummary }
     * 
     */
    public PermissionGroupSummary createPermissionGroupSummary() {
        return new PermissionGroupSummary();
    }

    /**
     * Create an instance of {@link ScheduleLog }
     * 
     */
    public ScheduleLog createScheduleLog() {
        return new ScheduleLog();
    }

    /**
     * Create an instance of {@link DashboardBookmark }
     * 
     */
    public DashboardBookmark createDashboardBookmark() {
        return new DashboardBookmark();
    }

    /**
     * Create an instance of {@link ReportSuiteCustomCalendar }
     * 
     */
    public ReportSuiteCustomCalendar createReportSuiteCustomCalendar() {
        return new ReportSuiteCustomCalendar();
    }

    /**
     * Create an instance of {@link ListVariable }
     * 
     */
    public ListVariable createListVariable() {
        return new ListVariable();
    }

    /**
     * Create an instance of {@link ReportElement }
     * 
     */
    public ReportElement createReportElement() {
        return new ReportElement();
    }

    /**
     * Create an instance of {@link DataSourceId }
     * 
     */
    public DataSourceId createDataSourceId() {
        return new DataSourceId();
    }

    /**
     * Create an instance of {@link SegmentRule }
     * 
     */
    public SegmentRule createSegmentRule() {
        return new SegmentRule();
    }

    /**
     * Create an instance of {@link ReportSuiteMarketingChannelExpiration }
     * 
     */
    public ReportSuiteMarketingChannelExpiration createReportSuiteMarketingChannelExpiration() {
        return new ReportSuiteMarketingChannelExpiration();
    }

    /**
     * Create an instance of {@link VideoSettings }
     * 
     */
    public VideoSettings createVideoSettings() {
        return new VideoSettings();
    }

    /**
     * Create an instance of {@link CompanyReportSuite }
     * 
     */
    public CompanyReportSuite createCompanyReportSuite() {
        return new CompanyReportSuite();
    }

    /**
     * Create an instance of {@link IpAddressExclusion }
     * 
     */
    public IpAddressExclusion createIpAddressExclusion() {
        return new IpAddressExclusion();
    }

    /**
     * Create an instance of {@link SegmentDefinition }
     * 
     */
    public SegmentDefinition createSegmentDefinition() {
        return new SegmentDefinition();
    }

    /**
     * Create an instance of {@link DataFeedsList }
     * 
     */
    public DataFeedsList createDataFeedsList() {
        return new DataFeedsList();
    }

    /**
     * Create an instance of {@link ReportDescriptionSegment }
     * 
     */
    public ReportDescriptionSegment createReportDescriptionSegment() {
        return new ReportDescriptionSegment();
    }

    /**
     * Create an instance of {@link Prop }
     * 
     */
    public Prop createProp() {
        return new Prop();
    }

    /**
     * Create an instance of {@link SegmentsSaveResponse }
     * 
     */
    public SegmentsSaveResponse createSegmentsSaveResponse() {
        return new SegmentsSaveResponse();
    }

    /**
     * Create an instance of {@link DashboardPage }
     * 
     */
    public DashboardPage createDashboardPage() {
        return new DashboardPage();
    }

    /**
     * Create an instance of {@link ClassificationsFtp }
     * 
     */
    public ClassificationsFtp createClassificationsFtp() {
        return new ClassificationsFtp();
    }

    /**
     * Create an instance of {@link ReportQueueItem }
     * 
     */
    public ReportQueueItem createReportQueueItem() {
        return new ReportQueueItem();
    }

    /**
     * Create an instance of {@link DataSourceSettings }
     * 
     */
    public DataSourceSettings createDataSourceSettings() {
        return new DataSourceSettings();
    }

    /**
     * Create an instance of {@link SegmentShare }
     * 
     */
    public SegmentShare createSegmentShare() {
        return new SegmentShare();
    }

    /**
     * Create an instance of {@link ReportQueueResponse }
     * 
     */
    public ReportQueueResponse createReportQueueResponse() {
        return new ReportQueueResponse();
    }

    /**
     * Create an instance of {@link ChannelValueAttribute }
     * 
     */
    public ChannelValueAttribute createChannelValueAttribute() {
        return new ChannelValueAttribute();
    }

    /**
     * Create an instance of {@link ReportSuiteDiscover }
     * 
     */
    public ReportSuiteDiscover createReportSuiteDiscover() {
        return new ReportSuiteDiscover();
    }

    /**
     * Create an instance of {@link ReportSuiteLocalization }
     * 
     */
    public ReportSuiteLocalization createReportSuiteLocalization() {
        return new ReportSuiteLocalization();
    }

    /**
     * Create an instance of {@link ReportSuiteKeyVisitors }
     * 
     */
    public ReportSuiteKeyVisitors createReportSuiteKeyVisitors() {
        return new ReportSuiteKeyVisitors();
    }

    /**
     * Create an instance of {@link MarketingChannelCost }
     * 
     */
    public MarketingChannelCost createMarketingChannelCost() {
        return new MarketingChannelCost();
    }

    /**
     * Create an instance of {@link DataSourceJob }
     * 
     */
    public DataSourceJob createDataSourceJob() {
        return new DataSourceJob();
    }

    /**
     * Create an instance of {@link FtpInfo }
     * 
     */
    public FtpInfo createFtpInfo() {
        return new FtpInfo();
    }

    /**
     * Create an instance of {@link PermanentTraffic }
     * 
     */
    public PermanentTraffic createPermanentTraffic() {
        return new PermanentTraffic();
    }

    /**
     * Create an instance of {@link ReportSuiteListVariable }
     * 
     */
    public ReportSuiteListVariable createReportSuiteListVariable() {
        return new ReportSuiteListVariable();
    }

    /**
     * Create an instance of {@link ReportSuiteMarketingChannels }
     * 
     */
    public ReportSuiteMarketingChannels createReportSuiteMarketingChannels() {
        return new ReportSuiteMarketingChannels();
    }

    /**
     * Create an instance of {@link StringArray }
     * 
     */
    public StringArray createStringArray() {
        return new StringArray();
    }

    /**
     * Create an instance of {@link ClassificationItem }
     * 
     */
    public ClassificationItem createClassificationItem() {
        return new ClassificationItem();
    }

    /**
     * Create an instance of {@link CompanyReportSuites }
     * 
     */
    public CompanyReportSuites createCompanyReportSuites() {
        return new CompanyReportSuites();
    }

    /**
     * Create an instance of {@link ReportDescriptionElement }
     * 
     */
    public ReportDescriptionElement createReportDescriptionElement() {
        return new ReportDescriptionElement();
    }

    /**
     * Create an instance of {@link ScheduledSpike }
     * 
     */
    public ScheduledSpike createScheduledSpike() {
        return new ScheduledSpike();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link DashboardDisplayInfo }
     * 
     */
    public DashboardDisplayInfo createDashboardDisplayInfo() {
        return new DashboardDisplayInfo();
    }

    /**
     * Create an instance of {@link DataSource }
     * 
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link ClassificationsFtpInfo }
     * 
     */
    public ClassificationsFtpInfo createClassificationsFtpInfo() {
        return new ClassificationsFtpInfo();
    }

    /**
     * Create an instance of {@link LoginFull }
     * 
     */
    public LoginFull createLoginFull() {
        return new LoginFull();
    }

    /**
     * Create an instance of {@link PaidSearchDetection }
     * 
     */
    public PaidSearchDetection createPaidSearchDetection() {
        return new PaidSearchDetection();
    }

    /**
     * Create an instance of {@link ReportSuiteSegments }
     * 
     */
    public ReportSuiteSegments createReportSuiteSegments() {
        return new ReportSuiteSegments();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link ReportDescriptionMetric }
     * 
     */
    public ReportDescriptionMetric createReportDescriptionMetric() {
        return new ReportDescriptionMetric();
    }

    /**
     * Create an instance of {@link SocialProperties }
     * 
     */
    public SocialProperties createSocialProperties() {
        return new SocialProperties();
    }

    /**
     * Create an instance of {@link BookmarkFolder }
     * 
     */
    public BookmarkFolder createBookmarkFolder() {
        return new BookmarkFolder();
    }

    /**
     * Create an instance of {@link ReportDataPath }
     * 
     */
    public ReportDataPath createReportDataPath() {
        return new ReportDataPath();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link ReportSuiteSiteTitle }
     * 
     */
    public ReportSuiteSiteTitle createReportSuiteSiteTitle() {
        return new ReportSuiteSiteTitle();
    }

    /**
     * Create an instance of {@link ReportSuiteActivation }
     * 
     */
    public ReportSuiteActivation createReportSuiteActivation() {
        return new ReportSuiteActivation();
    }

    /**
     * Create an instance of {@link HitAttribute }
     * 
     */
    public HitAttribute createHitAttribute() {
        return new HitAttribute();
    }

    /**
     * Create an instance of {@link ReportSegment }
     * 
     */
    public ReportSegment createReportSegment() {
        return new ReportSegment();
    }

    /**
     * Create an instance of {@link ReportSuiteIpObfuscation }
     * 
     */
    public ReportSuiteIpObfuscation createReportSuiteIpObfuscation() {
        return new ReportSuiteIpObfuscation();
    }

    /**
     * Create an instance of {@link SegmentContainer }
     * 
     */
    public SegmentContainer createSegmentContainer() {
        return new SegmentContainer();
    }

    /**
     * Create an instance of {@link ReportSuiteIpAddressExclusions }
     * 
     */
    public ReportSuiteIpAddressExclusions createReportSuiteIpAddressExclusions() {
        return new ReportSuiteIpAddressExclusions();
    }

    /**
     * Create an instance of {@link ReportSuiteSettings }
     * 
     */
    public ReportSuiteSettings createReportSuiteSettings() {
        return new ReportSuiteSettings();
    }

    /**
     * Create an instance of {@link ClassificationsCompatibilityElement }
     * 
     */
    public ClassificationsCompatibilityElement createClassificationsCompatibilityElement() {
        return new ClassificationsCompatibilityElement();
    }

    /**
     * Create an instance of {@link ReportData }
     * 
     */
    public ReportData createReportData() {
        return new ReportData();
    }

    /**
     * Create an instance of {@link ReportSuiteRealTimeSettings }
     * 
     */
    public ReportSuiteRealTimeSettings createReportSuiteRealTimeSettings() {
        return new ReportSuiteRealTimeSettings();
    }

    /**
     * Create an instance of {@link ReportSuiteTimeZone }
     * 
     */
    public ReportSuiteTimeZone createReportSuiteTimeZone() {
        return new ReportSuiteTimeZone();
    }

    /**
     * Create an instance of {@link ReportSuiteTransactionEnabled }
     * 
     */
    public ReportSuiteTransactionEnabled createReportSuiteTransactionEnabled() {
        return new ReportSuiteTransactionEnabled();
    }

    /**
     * Create an instance of {@link ElementClassifications }
     * 
     */
    public ElementClassifications createElementClassifications() {
        return new ElementClassifications();
    }

    /**
     * Create an instance of {@link RsMarketingChannelRulesets }
     * 
     */
    public RsMarketingChannelRulesets createRsMarketingChannelRulesets() {
        return new RsMarketingChannelRulesets();
    }

    /**
     * Create an instance of {@link ReportSuiteEvents }
     * 
     */
    public ReportSuiteEvents createReportSuiteEvents() {
        return new ReportSuiteEvents();
    }

    /**
     * Create an instance of {@link RealTimeSettings }
     * 
     */
    public RealTimeSettings createRealTimeSettings() {
        return new RealTimeSettings();
    }

    /**
     * Create an instance of {@link ReportSuiteAxleStartDate }
     * 
     */
    public ReportSuiteAxleStartDate createReportSuiteAxleStartDate() {
        return new ReportSuiteAxleStartDate();
    }

    /**
     * Create an instance of {@link ReportDescription }
     * 
     */
    public ReportDescription createReportDescription() {
        return new ReportDescription();
    }

    /**
     * Create an instance of {@link ScheduleRecurrenceParameter }
     * 
     */
    public ScheduleRecurrenceParameter createScheduleRecurrenceParameter() {
        return new ScheduleRecurrenceParameter();
    }

    /**
     * Create an instance of {@link ClassificationsJobStatus }
     * 
     */
    public ClassificationsJobStatus createClassificationsJobStatus() {
        return new ClassificationsJobStatus();
    }

    /**
     * Create an instance of {@link MarketingChannelRuleset }
     * 
     */
    public MarketingChannelRuleset createMarketingChannelRuleset() {
        return new MarketingChannelRuleset();
    }

    /**
     * Create an instance of {@link ReportSuiteProcessingStatus }
     * 
     */
    public ReportSuiteProcessingStatus createReportSuiteProcessingStatus() {
        return new ReportSuiteProcessingStatus();
    }

    /**
     * Create an instance of {@link TrackingServerData }
     * 
     */
    public TrackingServerData createTrackingServerData() {
        return new TrackingServerData();
    }

    /**
     * Create an instance of {@link SegmentFilters }
     * 
     */
    public SegmentFilters createSegmentFilters() {
        return new SegmentFilters();
    }

    /**
     * Create an instance of {@link ReportSuiteTemplate }
     * 
     */
    public ReportSuiteTemplate createReportSuiteTemplate() {
        return new ReportSuiteTemplate();
    }

    /**
     * Create an instance of {@link DataFeedActivity }
     * 
     */
    public DataFeedActivity createDataFeedActivity() {
        return new DataFeedActivity();
    }

    /**
     * Create an instance of {@link ReportSuiteEvars }
     * 
     */
    public ReportSuiteEvars createReportSuiteEvars() {
        return new ReportSuiteEvars();
    }

    /**
     * Create an instance of {@link ReportDescriptionSearch }
     * 
     */
    public ReportDescriptionSearch createReportDescriptionSearch() {
        return new ReportDescriptionSearch();
    }

    /**
     * Create an instance of {@link ReportSuiteDataWarehouseDisplay }
     * 
     */
    public ReportSuiteDataWarehouseDisplay createReportSuiteDataWarehouseDisplay() {
        return new ReportSuiteDataWarehouseDisplay();
    }

    /**
     * Create an instance of {@link ClassificationsFilters }
     * 
     */
    public ClassificationsFilters createClassificationsFilters() {
        return new ClassificationsFilters();
    }

    /**
     * Create an instance of {@link ClassificationsCreateJobResponse }
     * 
     */
    public ClassificationsCreateJobResponse createClassificationsCreateJobResponse() {
        return new ClassificationsCreateJobResponse();
    }

    /**
     * Create an instance of {@link DeliveryParameters }
     * 
     */
    public DeliveryParameters createDeliveryParameters() {
        return new DeliveryParameters();
    }

    /**
     * Create an instance of {@link TransactionStatus }
     * 
     */
    public TransactionStatus createTransactionStatus() {
        return new TransactionStatus();
    }

    /**
     * Create an instance of {@link ReportSuiteGroups }
     * 
     */
    public ReportSuiteGroups createReportSuiteGroups() {
        return new ReportSuiteGroups();
    }

    /**
     * Create an instance of {@link ReportSuiteProps }
     * 
     */
    public ReportSuiteProps createReportSuiteProps() {
        return new ReportSuiteProps();
    }

    /**
     * Create an instance of {@link PermissionGroup }
     * 
     */
    public PermissionGroup createPermissionGroup() {
        return new PermissionGroup();
    }

    /**
     * Create an instance of {@link BookmarkReturn }
     * 
     */
    public BookmarkReturn createBookmarkReturn() {
        return new BookmarkReturn();
    }

    /**
     * Create an instance of {@link ReportSuiteBaseUrl }
     * 
     */
    public ReportSuiteBaseUrl createReportSuiteBaseUrl() {
        return new ReportSuiteBaseUrl();
    }

    /**
     * Create an instance of {@link ScheduledReport }
     * 
     */
    public ScheduledReport createScheduledReport() {
        return new ScheduledReport();
    }

    /**
     * Create an instance of {@link SegmentRuleRestriction }
     * 
     */
    public SegmentRuleRestriction createSegmentRuleRestriction() {
        return new SegmentRuleRestriction();
    }

    /**
     * Create an instance of {@link ReportSuiteUniqueVisitorVariable }
     * 
     */
    public ReportSuiteUniqueVisitorVariable createReportSuiteUniqueVisitorVariable() {
        return new ReportSuiteUniqueVisitorVariable();
    }

    /**
     * Create an instance of {@link ProcessingStatus }
     * 
     */
    public ProcessingStatus createProcessingStatus() {
        return new ProcessingStatus();
    }

}
