//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for permission_group complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="permission_group">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="group_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="group_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="group_type" type="{http://marketing.adobe.com/analytics/2015/04/16}group_type_enum"/>
 *         &lt;element name="rsid_list" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="user_list" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="report_access_list" type="{http://marketing.adobe.com/analytics/2015/04/16}report_access" maxOccurs="unbounded"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "permission_group", propOrder = {

})
public class PermissionGroup {

    @XmlElement(name = "group_name", required = true)
    protected String groupName;
    @XmlElement(name = "group_description", required = true)
    protected String groupDescription;
    @XmlElement(name = "group_type", required = true)
    protected GroupTypeEnum groupType;
    @XmlElement(name = "rsid_list", required = true)
    protected List<String> rsidList;
    @XmlElement(name = "user_list", required = true)
    protected List<String> userList;
    @XmlElement(name = "report_access_list", required = true)
    protected List<ReportAccess> reportAccessList;

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the groupDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupDescription() {
        return groupDescription;
    }

    /**
     * Sets the value of the groupDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupDescription(String value) {
        this.groupDescription = value;
    }

    /**
     * Gets the value of the groupType property.
     * 
     * @return
     *     possible object is
     *     {@link GroupTypeEnum }
     *     
     */
    public GroupTypeEnum getGroupType() {
        return groupType;
    }

    /**
     * Sets the value of the groupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupTypeEnum }
     *     
     */
    public void setGroupType(GroupTypeEnum value) {
        this.groupType = value;
    }

    /**
     * Gets the value of the rsidList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rsidList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRsidList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRsidList() {
        if (rsidList == null) {
            rsidList = new ArrayList<String>();
        }
        return this.rsidList;
    }

    /**
     * Gets the value of the userList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUserList() {
        if (userList == null) {
            userList = new ArrayList<String>();
        }
        return this.userList;
    }

    /**
     * Gets the value of the reportAccessList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportAccessList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportAccessList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportAccess }
     * 
     * 
     */
    public List<ReportAccess> getReportAccessList() {
        if (reportAccessList == null) {
            reportAccessList = new ArrayList<ReportAccess>();
        }
        return this.reportAccessList;
    }

}
