//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for processing_status complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="processing_status">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="elevator_latency" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lobby_latency" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processing_status", propOrder = {

})
public class ProcessingStatus {

    @XmlElement(name = "elevator_latency")
    protected int elevatorLatency;
    @XmlElement(name = "lobby_latency")
    protected int lobbyLatency;

    /**
     * Gets the value of the elevatorLatency property.
     * 
     */
    public int getElevatorLatency() {
        return elevatorLatency;
    }

    /**
     * Sets the value of the elevatorLatency property.
     * 
     */
    public void setElevatorLatency(int value) {
        this.elevatorLatency = value;
    }

    /**
     * Gets the value of the lobbyLatency property.
     * 
     */
    public int getLobbyLatency() {
        return lobbyLatency;
    }

    /**
     * Sets the value of the lobbyLatency property.
     * 
     */
    public void setLobbyLatency(int value) {
        this.lobbyLatency = value;
    }

}
