//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for report_access_category_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="report_access_category_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ecommerce"/>
 *     &lt;enumeration value="traffic"/>
 *     &lt;enumeration value="paths"/>
 *     &lt;enumeration value="custom_paths"/>
 *     &lt;enumeration value="tools"/>
 *     &lt;enumeration value="search_center"/>
 *     &lt;enumeration value="tnt"/>
 *     &lt;enumeration value="video"/>
 *     &lt;enumeration value="web_services"/>
 *     &lt;enumeration value="admin_console"/>
 *     &lt;enumeration value="report_download"/>
 *     &lt;enumeration value="survey"/>
 *     &lt;enumeration value="advanced_reporting"/>
 *     &lt;enumeration value="social"/>
 *     &lt;enumeration value="social_publishing"/>
 *     &lt;enumeration value="data_connectors"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "report_access_category_enum")
@XmlEnum
public enum ReportAccessCategoryEnum {

    @XmlEnumValue("ecommerce")
    ECOMMERCE("ecommerce"),
    @XmlEnumValue("traffic")
    TRAFFIC("traffic"),
    @XmlEnumValue("paths")
    PATHS("paths"),
    @XmlEnumValue("custom_paths")
    CUSTOM_PATHS("custom_paths"),
    @XmlEnumValue("tools")
    TOOLS("tools"),
    @XmlEnumValue("search_center")
    SEARCH_CENTER("search_center"),
    @XmlEnumValue("tnt")
    TNT("tnt"),
    @XmlEnumValue("video")
    VIDEO("video"),
    @XmlEnumValue("web_services")
    WEB_SERVICES("web_services"),
    @XmlEnumValue("admin_console")
    ADMIN_CONSOLE("admin_console"),
    @XmlEnumValue("report_download")
    REPORT_DOWNLOAD("report_download"),
    @XmlEnumValue("survey")
    SURVEY("survey"),
    @XmlEnumValue("advanced_reporting")
    ADVANCED_REPORTING("advanced_reporting"),
    @XmlEnumValue("social")
    SOCIAL("social"),
    @XmlEnumValue("social_publishing")
    SOCIAL_PUBLISHING("social_publishing"),
    @XmlEnumValue("data_connectors")
    DATA_CONNECTORS("data_connectors");
    private final String value;

    ReportAccessCategoryEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReportAccessCategoryEnum fromValue(String v) {
        for (ReportAccessCategoryEnum c: ReportAccessCategoryEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
