//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for report_queue_item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="report_queue_item">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="reportID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="type" type="{http://marketing.adobe.com/analytics/2015/04/16}report_queue_item_type_enum"/>
 *         &lt;element name="queueTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://marketing.adobe.com/analytics/2015/04/16}report_queue_item_status_enum"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="estimate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="reportSuiteID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "report_queue_item", propOrder = {

})
public class ReportQueueItem {

    protected int reportID;
    @XmlElement(required = true)
    protected ReportQueueItemTypeEnum type;
    @XmlElement(required = true)
    protected String queueTime;
    @XmlElement(required = true)
    protected ReportQueueItemStatusEnum status;
    protected int priority;
    protected int estimate;
    @XmlElement(required = true)
    protected String reportSuiteID;
    @XmlElement(required = true)
    protected String user;

    /**
     * Gets the value of the reportID property.
     * 
     */
    public int getReportID() {
        return reportID;
    }

    /**
     * Sets the value of the reportID property.
     * 
     */
    public void setReportID(int value) {
        this.reportID = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ReportQueueItemTypeEnum }
     *     
     */
    public ReportQueueItemTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportQueueItemTypeEnum }
     *     
     */
    public void setType(ReportQueueItemTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the queueTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueueTime() {
        return queueTime;
    }

    /**
     * Sets the value of the queueTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueueTime(String value) {
        this.queueTime = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ReportQueueItemStatusEnum }
     *     
     */
    public ReportQueueItemStatusEnum getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportQueueItemStatusEnum }
     *     
     */
    public void setStatus(ReportQueueItemStatusEnum value) {
        this.status = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

    /**
     * Gets the value of the estimate property.
     * 
     */
    public int getEstimate() {
        return estimate;
    }

    /**
     * Sets the value of the estimate property.
     * 
     */
    public void setEstimate(int value) {
        this.estimate = value;
    }

    /**
     * Gets the value of the reportSuiteID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportSuiteID() {
        return reportSuiteID;
    }

    /**
     * Sets the value of the reportSuiteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportSuiteID(String value) {
        this.reportSuiteID = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

}
