//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for report_suite_settings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="report_suite_settings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="rsid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="site_title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="anchor_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="base_currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="base_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="calendar_type" type="{http://marketing.adobe.com/analytics/2015/04/16}custom_calendar_type_enum"/>
 *         &lt;element name="default_page" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="discover_enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ecommerce_level" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ecommerce_visits" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ecommerce_visitors" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="element_classifications" type="{http://marketing.adobe.com/analytics/2015/04/16}element_classifications" maxOccurs="unbounded"/>
 *         &lt;element name="elements" type="{http://marketing.adobe.com/analytics/2015/04/16}report" maxOccurs="unbounded"/>
 *         &lt;element name="ip_obfuscation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="metrics" type="{http://marketing.adobe.com/analytics/2015/04/16}report" maxOccurs="unbounded"/>
 *         &lt;element name="mobile_breakdowns" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="props" type="{http://marketing.adobe.com/analytics/2015/04/16}prop" maxOccurs="unbounded"/>
 *         &lt;element name="segments" type="{http://marketing.adobe.com/analytics/2015/04/16}segment_item" maxOccurs="unbounded"/>
 *         &lt;element name="template" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="time_zone" type="{http://marketing.adobe.com/analytics/2015/04/16}time_zone_enum"/>
 *         &lt;element name="unique_visitor_variable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="video_settings" type="{http://marketing.adobe.com/analytics/2015/04/16}video_settings"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "report_suite_settings", propOrder = {

})
public class ReportSuiteSettings {

    @XmlElement(required = true)
    protected String rsid;
    @XmlElement(name = "site_title", required = true)
    protected String siteTitle;
    protected boolean activation;
    @XmlElement(name = "anchor_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar anchorDate;
    @XmlElement(name = "base_currency", required = true)
    protected String baseCurrency;
    @XmlElement(name = "base_url", required = true)
    protected String baseUrl;
    @XmlElement(name = "calendar_type", required = true)
    protected String calendarType;
    @XmlElement(name = "default_page", required = true)
    protected String defaultPage;
    @XmlElement(name = "discover_enabled")
    protected boolean discoverEnabled;
    @XmlElement(name = "ecommerce_level")
    protected int ecommerceLevel;
    @XmlElement(name = "ecommerce_visits")
    protected int ecommerceVisits;
    @XmlElement(name = "ecommerce_visitors")
    protected int ecommerceVisitors;
    @XmlElement(name = "element_classifications", required = true)
    protected List<ElementClassifications> elementClassifications;
    @XmlElement(required = true)
    protected List<Report> elements;
    @XmlElement(name = "ip_obfuscation", required = true)
    protected String ipObfuscation;
    @XmlElement(required = true)
    protected List<Report> metrics;
    @XmlElement(name = "mobile_breakdowns", required = true)
    protected List<String> mobileBreakdowns;
    @XmlElement(required = true)
    protected List<Prop> props;
    @XmlElement(required = true)
    protected List<SegmentItem> segments;
    @XmlElement(required = true)
    protected String template;
    @XmlElement(name = "time_zone", required = true)
    protected TimeZoneEnum timeZone;
    @XmlElement(name = "unique_visitor_variable", required = true)
    protected String uniqueVisitorVariable;
    @XmlElement(name = "video_settings", required = true)
    protected VideoSettings videoSettings;

    /**
     * Gets the value of the rsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsid() {
        return rsid;
    }

    /**
     * Sets the value of the rsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsid(String value) {
        this.rsid = value;
    }

    /**
     * Gets the value of the siteTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteTitle() {
        return siteTitle;
    }

    /**
     * Sets the value of the siteTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteTitle(String value) {
        this.siteTitle = value;
    }

    /**
     * Gets the value of the activation property.
     * 
     */
    public boolean isActivation() {
        return activation;
    }

    /**
     * Sets the value of the activation property.
     * 
     */
    public void setActivation(boolean value) {
        this.activation = value;
    }

    /**
     * Gets the value of the anchorDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAnchorDate() {
        return anchorDate;
    }

    /**
     * Sets the value of the anchorDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAnchorDate(XMLGregorianCalendar value) {
        this.anchorDate = value;
    }

    /**
     * Gets the value of the baseCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCurrency() {
        return baseCurrency;
    }

    /**
     * Sets the value of the baseCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCurrency(String value) {
        this.baseCurrency = value;
    }

    /**
     * Gets the value of the baseUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseUrl() {
        return baseUrl;
    }

    /**
     * Sets the value of the baseUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseUrl(String value) {
        this.baseUrl = value;
    }

    /**
     * Gets the value of the calendarType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalendarType() {
        return calendarType;
    }

    /**
     * Sets the value of the calendarType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalendarType(String value) {
        this.calendarType = value;
    }

    /**
     * Gets the value of the defaultPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultPage() {
        return defaultPage;
    }

    /**
     * Sets the value of the defaultPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultPage(String value) {
        this.defaultPage = value;
    }

    /**
     * Gets the value of the discoverEnabled property.
     * 
     */
    public boolean isDiscoverEnabled() {
        return discoverEnabled;
    }

    /**
     * Sets the value of the discoverEnabled property.
     * 
     */
    public void setDiscoverEnabled(boolean value) {
        this.discoverEnabled = value;
    }

    /**
     * Gets the value of the ecommerceLevel property.
     * 
     */
    public int getEcommerceLevel() {
        return ecommerceLevel;
    }

    /**
     * Sets the value of the ecommerceLevel property.
     * 
     */
    public void setEcommerceLevel(int value) {
        this.ecommerceLevel = value;
    }

    /**
     * Gets the value of the ecommerceVisits property.
     * 
     */
    public int getEcommerceVisits() {
        return ecommerceVisits;
    }

    /**
     * Sets the value of the ecommerceVisits property.
     * 
     */
    public void setEcommerceVisits(int value) {
        this.ecommerceVisits = value;
    }

    /**
     * Gets the value of the ecommerceVisitors property.
     * 
     */
    public int getEcommerceVisitors() {
        return ecommerceVisitors;
    }

    /**
     * Sets the value of the ecommerceVisitors property.
     * 
     */
    public void setEcommerceVisitors(int value) {
        this.ecommerceVisitors = value;
    }

    /**
     * Gets the value of the elementClassifications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elementClassifications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElementClassifications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElementClassifications }
     * 
     * 
     */
    public List<ElementClassifications> getElementClassifications() {
        if (elementClassifications == null) {
            elementClassifications = new ArrayList<ElementClassifications>();
        }
        return this.elementClassifications;
    }

    /**
     * Gets the value of the elements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Report }
     * 
     * 
     */
    public List<Report> getElements() {
        if (elements == null) {
            elements = new ArrayList<Report>();
        }
        return this.elements;
    }

    /**
     * Gets the value of the ipObfuscation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpObfuscation() {
        return ipObfuscation;
    }

    /**
     * Sets the value of the ipObfuscation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpObfuscation(String value) {
        this.ipObfuscation = value;
    }

    /**
     * Gets the value of the metrics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metrics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetrics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Report }
     * 
     * 
     */
    public List<Report> getMetrics() {
        if (metrics == null) {
            metrics = new ArrayList<Report>();
        }
        return this.metrics;
    }

    /**
     * Gets the value of the mobileBreakdowns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mobileBreakdowns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMobileBreakdowns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMobileBreakdowns() {
        if (mobileBreakdowns == null) {
            mobileBreakdowns = new ArrayList<String>();
        }
        return this.mobileBreakdowns;
    }

    /**
     * Gets the value of the props property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the props property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Prop }
     * 
     * 
     */
    public List<Prop> getProps() {
        if (props == null) {
            props = new ArrayList<Prop>();
        }
        return this.props;
    }

    /**
     * Gets the value of the segments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegmentItem }
     * 
     * 
     */
    public List<SegmentItem> getSegments() {
        if (segments == null) {
            segments = new ArrayList<SegmentItem>();
        }
        return this.segments;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplate(String value) {
        this.template = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link TimeZoneEnum }
     *     
     */
    public TimeZoneEnum getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeZoneEnum }
     *     
     */
    public void setTimeZone(TimeZoneEnum value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the uniqueVisitorVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueVisitorVariable() {
        return uniqueVisitorVariable;
    }

    /**
     * Sets the value of the uniqueVisitorVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueVisitorVariable(String value) {
        this.uniqueVisitorVariable = value;
    }

    /**
     * Gets the value of the videoSettings property.
     * 
     * @return
     *     possible object is
     *     {@link VideoSettings }
     *     
     */
    public VideoSettings getVideoSettings() {
        return videoSettings;
    }

    /**
     * Sets the value of the videoSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoSettings }
     *     
     */
    public void setVideoSettings(VideoSettings value) {
        this.videoSettings = value;
    }

}
