//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scheduleRecurrenceParameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scheduleRecurrenceParameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="frequency" type="{http://marketing.adobe.com/analytics/2015/04/16}scheduleFrequency"/>
 *         &lt;element name="dayOfWeek" type="{http://marketing.adobe.com/analytics/2015/04/16}scheduleDayOfWeek"/>
 *         &lt;element name="dayOfMonth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="runHour" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="recurrence" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sequence" type="{http://marketing.adobe.com/analytics/2015/04/16}scheduleSequence"/>
 *         &lt;element name="cancelType" type="{http://marketing.adobe.com/analytics/2015/04/16}scheduleCancelType"/>
 *         &lt;element name="cancelOccurence" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="month" type="{http://marketing.adobe.com/analytics/2015/04/16}scheduleMonth"/>
 *         &lt;element name="timezoneOffset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scheduleRecurrenceParameter", propOrder = {

})
public class ScheduleRecurrenceParameter {

    @XmlElement(required = true)
    protected ScheduleFrequency frequency;
    @XmlElement(required = true)
    protected ScheduleDayOfWeek dayOfWeek;
    protected int dayOfMonth;
    protected int runHour;
    protected int recurrence;
    @XmlElement(required = true)
    protected String startDate;
    @XmlElement(required = true)
    protected String endDate;
    @XmlElement(required = true)
    protected ScheduleSequence sequence;
    @XmlElement(required = true)
    protected ScheduleCancelType cancelType;
    protected int cancelOccurence;
    @XmlElement(required = true, nillable = true)
    protected ScheduleMonth month;
    @XmlElement(required = true)
    protected String timezoneOffset;

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleFrequency }
     *     
     */
    public ScheduleFrequency getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleFrequency }
     *     
     */
    public void setFrequency(ScheduleFrequency value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the dayOfWeek property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleDayOfWeek }
     *     
     */
    public ScheduleDayOfWeek getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * Sets the value of the dayOfWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleDayOfWeek }
     *     
     */
    public void setDayOfWeek(ScheduleDayOfWeek value) {
        this.dayOfWeek = value;
    }

    /**
     * Gets the value of the dayOfMonth property.
     * 
     */
    public int getDayOfMonth() {
        return dayOfMonth;
    }

    /**
     * Sets the value of the dayOfMonth property.
     * 
     */
    public void setDayOfMonth(int value) {
        this.dayOfMonth = value;
    }

    /**
     * Gets the value of the runHour property.
     * 
     */
    public int getRunHour() {
        return runHour;
    }

    /**
     * Sets the value of the runHour property.
     * 
     */
    public void setRunHour(int value) {
        this.runHour = value;
    }

    /**
     * Gets the value of the recurrence property.
     * 
     */
    public int getRecurrence() {
        return recurrence;
    }

    /**
     * Sets the value of the recurrence property.
     * 
     */
    public void setRecurrence(int value) {
        this.recurrence = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleSequence }
     *     
     */
    public ScheduleSequence getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleSequence }
     *     
     */
    public void setSequence(ScheduleSequence value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the cancelType property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleCancelType }
     *     
     */
    public ScheduleCancelType getCancelType() {
        return cancelType;
    }

    /**
     * Sets the value of the cancelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleCancelType }
     *     
     */
    public void setCancelType(ScheduleCancelType value) {
        this.cancelType = value;
    }

    /**
     * Gets the value of the cancelOccurence property.
     * 
     */
    public int getCancelOccurence() {
        return cancelOccurence;
    }

    /**
     * Sets the value of the cancelOccurence property.
     * 
     */
    public void setCancelOccurence(int value) {
        this.cancelOccurence = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleMonth }
     *     
     */
    public ScheduleMonth getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleMonth }
     *     
     */
    public void setMonth(ScheduleMonth value) {
        this.month = value;
    }

    /**
     * Gets the value of the timezoneOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezoneOffset() {
        return timezoneOffset;
    }

    /**
     * Sets the value of the timezoneOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezoneOffset(String value) {
        this.timezoneOffset = value;
    }

}
