//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scheduleFrequency.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="scheduleFrequency">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Run Once"/>
 *     &lt;enumeration value="Hourly"/>
 *     &lt;enumeration value="Daily By Days"/>
 *     &lt;enumeration value="Daily weekdays"/>
 *     &lt;enumeration value="Weekly"/>
 *     &lt;enumeration value="Monthly by DOM"/>
 *     &lt;enumeration value="Monthly by week"/>
 *     &lt;enumeration value="Yearly by DOM"/>
 *     &lt;enumeration value="Yearly by Week"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "scheduleFrequency")
@XmlEnum
public enum ScheduleFrequency {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Run Once")
    RUN_ONCE("Run Once"),
    @XmlEnumValue("Hourly")
    HOURLY("Hourly"),
    @XmlEnumValue("Daily By Days")
    DAILY_BY_DAYS("Daily By Days"),
    @XmlEnumValue("Daily weekdays")
    DAILY_WEEKDAYS("Daily weekdays"),
    @XmlEnumValue("Weekly")
    WEEKLY("Weekly"),
    @XmlEnumValue("Monthly by DOM")
    MONTHLY_BY_DOM("Monthly by DOM"),
    @XmlEnumValue("Monthly by week")
    MONTHLY_BY_WEEK("Monthly by week"),
    @XmlEnumValue("Yearly by DOM")
    YEARLY_BY_DOM("Yearly by DOM"),
    @XmlEnumValue("Yearly by Week")
    YEARLY_BY_WEEK("Yearly by Week");
    private final String value;

    ScheduleFrequency(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScheduleFrequency fromValue(String v) {
        for (ScheduleFrequency c: ScheduleFrequency.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
