//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scheduledReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scheduledReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="scheduleRecurrenceParameter" type="{http://marketing.adobe.com/analytics/2015/04/16}scheduleRecurrenceParameter"/>
 *         &lt;element name="deliveryParameters" type="{http://marketing.adobe.com/analytics/2015/04/16}deliveryParameters"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="reportSuiteID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isFailed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="excelWorkbook" type="{http://marketing.adobe.com/analytics/2015/04/16}excelWorkbook"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scheduledReport", propOrder = {

})
public class ScheduledReport {

    @XmlElement(required = true)
    protected ScheduleRecurrenceParameter scheduleRecurrenceParameter;
    @XmlElement(required = true)
    protected DeliveryParameters deliveryParameters;
    protected int id;
    @XmlElement(required = true)
    protected String reportSuiteID;
    protected boolean isFailed;
    @XmlElement(required = true)
    protected ExcelWorkbook excelWorkbook;

    /**
     * Gets the value of the scheduleRecurrenceParameter property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleRecurrenceParameter }
     *     
     */
    public ScheduleRecurrenceParameter getScheduleRecurrenceParameter() {
        return scheduleRecurrenceParameter;
    }

    /**
     * Sets the value of the scheduleRecurrenceParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleRecurrenceParameter }
     *     
     */
    public void setScheduleRecurrenceParameter(ScheduleRecurrenceParameter value) {
        this.scheduleRecurrenceParameter = value;
    }

    /**
     * Gets the value of the deliveryParameters property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryParameters }
     *     
     */
    public DeliveryParameters getDeliveryParameters() {
        return deliveryParameters;
    }

    /**
     * Sets the value of the deliveryParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryParameters }
     *     
     */
    public void setDeliveryParameters(DeliveryParameters value) {
        this.deliveryParameters = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the reportSuiteID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportSuiteID() {
        return reportSuiteID;
    }

    /**
     * Sets the value of the reportSuiteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportSuiteID(String value) {
        this.reportSuiteID = value;
    }

    /**
     * Gets the value of the isFailed property.
     * 
     */
    public boolean isIsFailed() {
        return isFailed;
    }

    /**
     * Sets the value of the isFailed property.
     * 
     */
    public void setIsFailed(boolean value) {
        this.isFailed = value;
    }

    /**
     * Gets the value of the excelWorkbook property.
     * 
     * @return
     *     possible object is
     *     {@link ExcelWorkbook }
     *     
     */
    public ExcelWorkbook getExcelWorkbook() {
        return excelWorkbook;
    }

    /**
     * Sets the value of the excelWorkbook property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExcelWorkbook }
     *     
     */
    public void setExcelWorkbook(ExcelWorkbook value) {
        this.excelWorkbook = value;
    }

}
