//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for time_zone_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="time_zone_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Europe/London"/>
 *     &lt;enumeration value="US/Samoa"/>
 *     &lt;enumeration value="US/Hawaii"/>
 *     &lt;enumeration value="US/Alaska"/>
 *     &lt;enumeration value="America/Tijuana"/>
 *     &lt;enumeration value="US/Pacific"/>
 *     &lt;enumeration value="US/Arizona"/>
 *     &lt;enumeration value="US/Mountain"/>
 *     &lt;enumeration value="America/Mexico_City"/>
 *     &lt;enumeration value="Canada/Saskatchewan"/>
 *     &lt;enumeration value="US/Central"/>
 *     &lt;enumeration value="America/Lima"/>
 *     &lt;enumeration value="US/Eastern"/>
 *     &lt;enumeration value="US/East-Indiana"/>
 *     &lt;enumeration value="America/Caracas"/>
 *     &lt;enumeration value="Canada/Atlantic"/>
 *     &lt;enumeration value="America/Santiago"/>
 *     &lt;enumeration value="America/La_Paz"/>
 *     &lt;enumeration value="Canada/Newfoundland"/>
 *     &lt;enumeration value="America/Sao_Paulo"/>
 *     &lt;enumeration value="America/Buenos_Aires"/>
 *     &lt;enumeration value="America/Guyana"/>
 *     &lt;enumeration value="America/Montevideo"/>
 *     &lt;enumeration value="Etc/GMT+2"/>
 *     &lt;enumeration value="Atlantic/Azores"/>
 *     &lt;enumeration value="Atlantic/Cape_Verde"/>
 *     &lt;enumeration value="GMT"/>
 *     &lt;enumeration value="Europe/Berlin"/>
 *     &lt;enumeration value="Europe/Paris"/>
 *     &lt;enumeration value="Europe/Prague"/>
 *     &lt;enumeration value="Europe/Warsaw"/>
 *     &lt;enumeration value="Europe/Athens"/>
 *     &lt;enumeration value="Africa/Cairo"/>
 *     &lt;enumeration value="EET"/>
 *     &lt;enumeration value="Africa/Harare"/>
 *     &lt;enumeration value="Israel"/>
 *     &lt;enumeration value="Europe/Istanbul"/>
 *     &lt;enumeration value="Asia/Baghdad"/>
 *     &lt;enumeration value="Asia/Kuwait"/>
 *     &lt;enumeration value="Asia/Tehran"/>
 *     &lt;enumeration value="Asia/Muscat"/>
 *     &lt;enumeration value="Europe/Samara"/>
 *     &lt;enumeration value="Europe/Moscow"/>
 *     &lt;enumeration value="Asia/Tbilisi"/>
 *     &lt;enumeration value="Europe/Volgograd"/>
 *     &lt;enumeration value="Asia/Kabul"/>
 *     &lt;enumeration value="Asia/Yekaterinburg"/>
 *     &lt;enumeration value="Asia/Karachi"/>
 *     &lt;enumeration value="Asia/Tashkent"/>
 *     &lt;enumeration value="Asia/Calcutta"/>
 *     &lt;enumeration value="Asia/Colombo"/>
 *     &lt;enumeration value="Asia/Almaty"/>
 *     &lt;enumeration value="Asia/Dhaka"/>
 *     &lt;enumeration value="Asia/Bangkok"/>
 *     &lt;enumeration value="Asia/Chongqing"/>
 *     &lt;enumeration value="Asia/Hong_Kong"/>
 *     &lt;enumeration value="Australia/Perth"/>
 *     &lt;enumeration value="Asia/Tokyo"/>
 *     &lt;enumeration value="Asia/Yakutsk"/>
 *     &lt;enumeration value="Australia/Adelaide"/>
 *     &lt;enumeration value="Australia/Darwin"/>
 *     &lt;enumeration value="Australia/Brisbane"/>
 *     &lt;enumeration value="Australia/Sydney"/>
 *     &lt;enumeration value="Pacific/Guam"/>
 *     &lt;enumeration value="Australia/Hobart"/>
 *     &lt;enumeration value="Pacific/Port_Moresby"/>
 *     &lt;enumeration value="Asia/Vladivostok"/>
 *     &lt;enumeration value="Asia/Magadan"/>
 *     &lt;enumeration value="Pacific/Guadalcanal"/>
 *     &lt;enumeration value="Pacific/Kwajalein"/>
 *     &lt;enumeration value="Pacific/Fiji"/>
 *     &lt;enumeration value="Asia/Kamchatka"/>
 *     &lt;enumeration value="Pacific/Majuro"/>
 *     &lt;enumeration value="NZ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "time_zone_enum")
@XmlEnum
public enum TimeZoneEnum {

    @XmlEnumValue("Europe/London")
    EUROPE_LONDON("Europe/London"),
    @XmlEnumValue("US/Samoa")
    US_SAMOA("US/Samoa"),
    @XmlEnumValue("US/Hawaii")
    US_HAWAII("US/Hawaii"),
    @XmlEnumValue("US/Alaska")
    US_ALASKA("US/Alaska"),
    @XmlEnumValue("America/Tijuana")
    AMERICA_TIJUANA("America/Tijuana"),
    @XmlEnumValue("US/Pacific")
    US_PACIFIC("US/Pacific"),
    @XmlEnumValue("US/Arizona")
    US_ARIZONA("US/Arizona"),
    @XmlEnumValue("US/Mountain")
    US_MOUNTAIN("US/Mountain"),
    @XmlEnumValue("America/Mexico_City")
    AMERICA_MEXICO_CITY("America/Mexico_City"),
    @XmlEnumValue("Canada/Saskatchewan")
    CANADA_SASKATCHEWAN("Canada/Saskatchewan"),
    @XmlEnumValue("US/Central")
    US_CENTRAL("US/Central"),
    @XmlEnumValue("America/Lima")
    AMERICA_LIMA("America/Lima"),
    @XmlEnumValue("US/Eastern")
    US_EASTERN("US/Eastern"),
    @XmlEnumValue("US/East-Indiana")
    US_EAST_INDIANA("US/East-Indiana"),
    @XmlEnumValue("America/Caracas")
    AMERICA_CARACAS("America/Caracas"),
    @XmlEnumValue("Canada/Atlantic")
    CANADA_ATLANTIC("Canada/Atlantic"),
    @XmlEnumValue("America/Santiago")
    AMERICA_SANTIAGO("America/Santiago"),
    @XmlEnumValue("America/La_Paz")
    AMERICA_LA_PAZ("America/La_Paz"),
    @XmlEnumValue("Canada/Newfoundland")
    CANADA_NEWFOUNDLAND("Canada/Newfoundland"),
    @XmlEnumValue("America/Sao_Paulo")
    AMERICA_SAO_PAULO("America/Sao_Paulo"),
    @XmlEnumValue("America/Buenos_Aires")
    AMERICA_BUENOS_AIRES("America/Buenos_Aires"),
    @XmlEnumValue("America/Guyana")
    AMERICA_GUYANA("America/Guyana"),
    @XmlEnumValue("America/Montevideo")
    AMERICA_MONTEVIDEO("America/Montevideo"),
    @XmlEnumValue("Etc/GMT+2")
    ETC_GMT_2("Etc/GMT+2"),
    @XmlEnumValue("Atlantic/Azores")
    ATLANTIC_AZORES("Atlantic/Azores"),
    @XmlEnumValue("Atlantic/Cape_Verde")
    ATLANTIC_CAPE_VERDE("Atlantic/Cape_Verde"),
    GMT("GMT"),
    @XmlEnumValue("Europe/Berlin")
    EUROPE_BERLIN("Europe/Berlin"),
    @XmlEnumValue("Europe/Paris")
    EUROPE_PARIS("Europe/Paris"),
    @XmlEnumValue("Europe/Prague")
    EUROPE_PRAGUE("Europe/Prague"),
    @XmlEnumValue("Europe/Warsaw")
    EUROPE_WARSAW("Europe/Warsaw"),
    @XmlEnumValue("Europe/Athens")
    EUROPE_ATHENS("Europe/Athens"),
    @XmlEnumValue("Africa/Cairo")
    AFRICA_CAIRO("Africa/Cairo"),
    EET("EET"),
    @XmlEnumValue("Africa/Harare")
    AFRICA_HARARE("Africa/Harare"),
    @XmlEnumValue("Israel")
    ISRAEL("Israel"),
    @XmlEnumValue("Europe/Istanbul")
    EUROPE_ISTANBUL("Europe/Istanbul"),
    @XmlEnumValue("Asia/Baghdad")
    ASIA_BAGHDAD("Asia/Baghdad"),
    @XmlEnumValue("Asia/Kuwait")
    ASIA_KUWAIT("Asia/Kuwait"),
    @XmlEnumValue("Asia/Tehran")
    ASIA_TEHRAN("Asia/Tehran"),
    @XmlEnumValue("Asia/Muscat")
    ASIA_MUSCAT("Asia/Muscat"),
    @XmlEnumValue("Europe/Samara")
    EUROPE_SAMARA("Europe/Samara"),
    @XmlEnumValue("Europe/Moscow")
    EUROPE_MOSCOW("Europe/Moscow"),
    @XmlEnumValue("Asia/Tbilisi")
    ASIA_TBILISI("Asia/Tbilisi"),
    @XmlEnumValue("Europe/Volgograd")
    EUROPE_VOLGOGRAD("Europe/Volgograd"),
    @XmlEnumValue("Asia/Kabul")
    ASIA_KABUL("Asia/Kabul"),
    @XmlEnumValue("Asia/Yekaterinburg")
    ASIA_YEKATERINBURG("Asia/Yekaterinburg"),
    @XmlEnumValue("Asia/Karachi")
    ASIA_KARACHI("Asia/Karachi"),
    @XmlEnumValue("Asia/Tashkent")
    ASIA_TASHKENT("Asia/Tashkent"),
    @XmlEnumValue("Asia/Calcutta")
    ASIA_CALCUTTA("Asia/Calcutta"),
    @XmlEnumValue("Asia/Colombo")
    ASIA_COLOMBO("Asia/Colombo"),
    @XmlEnumValue("Asia/Almaty")
    ASIA_ALMATY("Asia/Almaty"),
    @XmlEnumValue("Asia/Dhaka")
    ASIA_DHAKA("Asia/Dhaka"),
    @XmlEnumValue("Asia/Bangkok")
    ASIA_BANGKOK("Asia/Bangkok"),
    @XmlEnumValue("Asia/Chongqing")
    ASIA_CHONGQING("Asia/Chongqing"),
    @XmlEnumValue("Asia/Hong_Kong")
    ASIA_HONG_KONG("Asia/Hong_Kong"),
    @XmlEnumValue("Australia/Perth")
    AUSTRALIA_PERTH("Australia/Perth"),
    @XmlEnumValue("Asia/Tokyo")
    ASIA_TOKYO("Asia/Tokyo"),
    @XmlEnumValue("Asia/Yakutsk")
    ASIA_YAKUTSK("Asia/Yakutsk"),
    @XmlEnumValue("Australia/Adelaide")
    AUSTRALIA_ADELAIDE("Australia/Adelaide"),
    @XmlEnumValue("Australia/Darwin")
    AUSTRALIA_DARWIN("Australia/Darwin"),
    @XmlEnumValue("Australia/Brisbane")
    AUSTRALIA_BRISBANE("Australia/Brisbane"),
    @XmlEnumValue("Australia/Sydney")
    AUSTRALIA_SYDNEY("Australia/Sydney"),
    @XmlEnumValue("Pacific/Guam")
    PACIFIC_GUAM("Pacific/Guam"),
    @XmlEnumValue("Australia/Hobart")
    AUSTRALIA_HOBART("Australia/Hobart"),
    @XmlEnumValue("Pacific/Port_Moresby")
    PACIFIC_PORT_MORESBY("Pacific/Port_Moresby"),
    @XmlEnumValue("Asia/Vladivostok")
    ASIA_VLADIVOSTOK("Asia/Vladivostok"),
    @XmlEnumValue("Asia/Magadan")
    ASIA_MAGADAN("Asia/Magadan"),
    @XmlEnumValue("Pacific/Guadalcanal")
    PACIFIC_GUADALCANAL("Pacific/Guadalcanal"),
    @XmlEnumValue("Pacific/Kwajalein")
    PACIFIC_KWAJALEIN("Pacific/Kwajalein"),
    @XmlEnumValue("Pacific/Fiji")
    PACIFIC_FIJI("Pacific/Fiji"),
    @XmlEnumValue("Asia/Kamchatka")
    ASIA_KAMCHATKA("Asia/Kamchatka"),
    @XmlEnumValue("Pacific/Majuro")
    PACIFIC_MAJURO("Pacific/Majuro"),
    NZ("NZ");
    private final String value;

    TimeZoneEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimeZoneEnum fromValue(String v) {
        for (TimeZoneEnum c: TimeZoneEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
