//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unique_visitor_variable_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="unique_visitor_variable_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="::none::"/>
 *     &lt;enumeration value="evar1"/>
 *     &lt;enumeration value="evar2"/>
 *     &lt;enumeration value="evar3"/>
 *     &lt;enumeration value="evar4"/>
 *     &lt;enumeration value="evar5"/>
 *     &lt;enumeration value="evar6"/>
 *     &lt;enumeration value="evar7"/>
 *     &lt;enumeration value="evar8"/>
 *     &lt;enumeration value="evar9"/>
 *     &lt;enumeration value="evar10"/>
 *     &lt;enumeration value="evar11"/>
 *     &lt;enumeration value="evar12"/>
 *     &lt;enumeration value="evar13"/>
 *     &lt;enumeration value="evar14"/>
 *     &lt;enumeration value="evar15"/>
 *     &lt;enumeration value="evar16"/>
 *     &lt;enumeration value="evar17"/>
 *     &lt;enumeration value="evar18"/>
 *     &lt;enumeration value="evar19"/>
 *     &lt;enumeration value="evar20"/>
 *     &lt;enumeration value="evar21"/>
 *     &lt;enumeration value="evar22"/>
 *     &lt;enumeration value="evar23"/>
 *     &lt;enumeration value="evar24"/>
 *     &lt;enumeration value="evar25"/>
 *     &lt;enumeration value="evar26"/>
 *     &lt;enumeration value="evar27"/>
 *     &lt;enumeration value="evar28"/>
 *     &lt;enumeration value="evar29"/>
 *     &lt;enumeration value="evar30"/>
 *     &lt;enumeration value="evar31"/>
 *     &lt;enumeration value="evar32"/>
 *     &lt;enumeration value="evar33"/>
 *     &lt;enumeration value="evar34"/>
 *     &lt;enumeration value="evar35"/>
 *     &lt;enumeration value="evar36"/>
 *     &lt;enumeration value="evar37"/>
 *     &lt;enumeration value="evar38"/>
 *     &lt;enumeration value="evar39"/>
 *     &lt;enumeration value="evar40"/>
 *     &lt;enumeration value="evar41"/>
 *     &lt;enumeration value="evar42"/>
 *     &lt;enumeration value="evar43"/>
 *     &lt;enumeration value="evar44"/>
 *     &lt;enumeration value="evar45"/>
 *     &lt;enumeration value="evar46"/>
 *     &lt;enumeration value="evar47"/>
 *     &lt;enumeration value="evar48"/>
 *     &lt;enumeration value="evar49"/>
 *     &lt;enumeration value="evar50"/>
 *     &lt;enumeration value="evar51"/>
 *     &lt;enumeration value="evar52"/>
 *     &lt;enumeration value="evar53"/>
 *     &lt;enumeration value="evar54"/>
 *     &lt;enumeration value="evar55"/>
 *     &lt;enumeration value="evar56"/>
 *     &lt;enumeration value="evar57"/>
 *     &lt;enumeration value="evar58"/>
 *     &lt;enumeration value="evar59"/>
 *     &lt;enumeration value="evar60"/>
 *     &lt;enumeration value="evar61"/>
 *     &lt;enumeration value="evar62"/>
 *     &lt;enumeration value="evar63"/>
 *     &lt;enumeration value="evar64"/>
 *     &lt;enumeration value="evar65"/>
 *     &lt;enumeration value="evar66"/>
 *     &lt;enumeration value="evar67"/>
 *     &lt;enumeration value="evar68"/>
 *     &lt;enumeration value="evar69"/>
 *     &lt;enumeration value="evar70"/>
 *     &lt;enumeration value="evar71"/>
 *     &lt;enumeration value="evar72"/>
 *     &lt;enumeration value="evar73"/>
 *     &lt;enumeration value="evar74"/>
 *     &lt;enumeration value="evar75"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "unique_visitor_variable_enum")
@XmlEnum
public enum UniqueVisitorVariableEnum {

    @XmlEnumValue("::none::")
    NONE("::none::"),
    @XmlEnumValue("evar1")
    EVAR_1("evar1"),
    @XmlEnumValue("evar2")
    EVAR_2("evar2"),
    @XmlEnumValue("evar3")
    EVAR_3("evar3"),
    @XmlEnumValue("evar4")
    EVAR_4("evar4"),
    @XmlEnumValue("evar5")
    EVAR_5("evar5"),
    @XmlEnumValue("evar6")
    EVAR_6("evar6"),
    @XmlEnumValue("evar7")
    EVAR_7("evar7"),
    @XmlEnumValue("evar8")
    EVAR_8("evar8"),
    @XmlEnumValue("evar9")
    EVAR_9("evar9"),
    @XmlEnumValue("evar10")
    EVAR_10("evar10"),
    @XmlEnumValue("evar11")
    EVAR_11("evar11"),
    @XmlEnumValue("evar12")
    EVAR_12("evar12"),
    @XmlEnumValue("evar13")
    EVAR_13("evar13"),
    @XmlEnumValue("evar14")
    EVAR_14("evar14"),
    @XmlEnumValue("evar15")
    EVAR_15("evar15"),
    @XmlEnumValue("evar16")
    EVAR_16("evar16"),
    @XmlEnumValue("evar17")
    EVAR_17("evar17"),
    @XmlEnumValue("evar18")
    EVAR_18("evar18"),
    @XmlEnumValue("evar19")
    EVAR_19("evar19"),
    @XmlEnumValue("evar20")
    EVAR_20("evar20"),
    @XmlEnumValue("evar21")
    EVAR_21("evar21"),
    @XmlEnumValue("evar22")
    EVAR_22("evar22"),
    @XmlEnumValue("evar23")
    EVAR_23("evar23"),
    @XmlEnumValue("evar24")
    EVAR_24("evar24"),
    @XmlEnumValue("evar25")
    EVAR_25("evar25"),
    @XmlEnumValue("evar26")
    EVAR_26("evar26"),
    @XmlEnumValue("evar27")
    EVAR_27("evar27"),
    @XmlEnumValue("evar28")
    EVAR_28("evar28"),
    @XmlEnumValue("evar29")
    EVAR_29("evar29"),
    @XmlEnumValue("evar30")
    EVAR_30("evar30"),
    @XmlEnumValue("evar31")
    EVAR_31("evar31"),
    @XmlEnumValue("evar32")
    EVAR_32("evar32"),
    @XmlEnumValue("evar33")
    EVAR_33("evar33"),
    @XmlEnumValue("evar34")
    EVAR_34("evar34"),
    @XmlEnumValue("evar35")
    EVAR_35("evar35"),
    @XmlEnumValue("evar36")
    EVAR_36("evar36"),
    @XmlEnumValue("evar37")
    EVAR_37("evar37"),
    @XmlEnumValue("evar38")
    EVAR_38("evar38"),
    @XmlEnumValue("evar39")
    EVAR_39("evar39"),
    @XmlEnumValue("evar40")
    EVAR_40("evar40"),
    @XmlEnumValue("evar41")
    EVAR_41("evar41"),
    @XmlEnumValue("evar42")
    EVAR_42("evar42"),
    @XmlEnumValue("evar43")
    EVAR_43("evar43"),
    @XmlEnumValue("evar44")
    EVAR_44("evar44"),
    @XmlEnumValue("evar45")
    EVAR_45("evar45"),
    @XmlEnumValue("evar46")
    EVAR_46("evar46"),
    @XmlEnumValue("evar47")
    EVAR_47("evar47"),
    @XmlEnumValue("evar48")
    EVAR_48("evar48"),
    @XmlEnumValue("evar49")
    EVAR_49("evar49"),
    @XmlEnumValue("evar50")
    EVAR_50("evar50"),
    @XmlEnumValue("evar51")
    EVAR_51("evar51"),
    @XmlEnumValue("evar52")
    EVAR_52("evar52"),
    @XmlEnumValue("evar53")
    EVAR_53("evar53"),
    @XmlEnumValue("evar54")
    EVAR_54("evar54"),
    @XmlEnumValue("evar55")
    EVAR_55("evar55"),
    @XmlEnumValue("evar56")
    EVAR_56("evar56"),
    @XmlEnumValue("evar57")
    EVAR_57("evar57"),
    @XmlEnumValue("evar58")
    EVAR_58("evar58"),
    @XmlEnumValue("evar59")
    EVAR_59("evar59"),
    @XmlEnumValue("evar60")
    EVAR_60("evar60"),
    @XmlEnumValue("evar61")
    EVAR_61("evar61"),
    @XmlEnumValue("evar62")
    EVAR_62("evar62"),
    @XmlEnumValue("evar63")
    EVAR_63("evar63"),
    @XmlEnumValue("evar64")
    EVAR_64("evar64"),
    @XmlEnumValue("evar65")
    EVAR_65("evar65"),
    @XmlEnumValue("evar66")
    EVAR_66("evar66"),
    @XmlEnumValue("evar67")
    EVAR_67("evar67"),
    @XmlEnumValue("evar68")
    EVAR_68("evar68"),
    @XmlEnumValue("evar69")
    EVAR_69("evar69"),
    @XmlEnumValue("evar70")
    EVAR_70("evar70"),
    @XmlEnumValue("evar71")
    EVAR_71("evar71"),
    @XmlEnumValue("evar72")
    EVAR_72("evar72"),
    @XmlEnumValue("evar73")
    EVAR_73("evar73"),
    @XmlEnumValue("evar74")
    EVAR_74("evar74"),
    @XmlEnumValue("evar75")
    EVAR_75("evar75");
    private final String value;

    UniqueVisitorVariableEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UniqueVisitorVariableEnum fromValue(String v) {
        for (UniqueVisitorVariableEnum c: UniqueVisitorVariableEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
