//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 11:03:57 AM CEST 
//


package com.adobe.analytics.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for video_settings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="video_settings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="core_enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ad_tracking_enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="chapter_tracking_enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="using_custom_variables" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="video_name_evar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="content_type_evar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="video_time_event" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="video_views_event" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="video_completes_event" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "video_settings", propOrder = {

})
public class VideoSettings {

    @XmlElement(name = "core_enabled")
    protected boolean coreEnabled;
    @XmlElement(name = "ad_tracking_enabled")
    protected boolean adTrackingEnabled;
    @XmlElement(name = "chapter_tracking_enabled")
    protected boolean chapterTrackingEnabled;
    @XmlElement(name = "using_custom_variables")
    protected boolean usingCustomVariables;
    @XmlElement(name = "video_name_evar", required = true)
    protected String videoNameEvar;
    @XmlElement(name = "content_type_evar", required = true)
    protected String contentTypeEvar;
    @XmlElement(name = "video_time_event", required = true)
    protected String videoTimeEvent;
    @XmlElement(name = "video_views_event", required = true)
    protected String videoViewsEvent;
    @XmlElement(name = "video_completes_event", required = true)
    protected String videoCompletesEvent;

    /**
     * Gets the value of the coreEnabled property.
     * 
     */
    public boolean isCoreEnabled() {
        return coreEnabled;
    }

    /**
     * Sets the value of the coreEnabled property.
     * 
     */
    public void setCoreEnabled(boolean value) {
        this.coreEnabled = value;
    }

    /**
     * Gets the value of the adTrackingEnabled property.
     * 
     */
    public boolean isAdTrackingEnabled() {
        return adTrackingEnabled;
    }

    /**
     * Sets the value of the adTrackingEnabled property.
     * 
     */
    public void setAdTrackingEnabled(boolean value) {
        this.adTrackingEnabled = value;
    }

    /**
     * Gets the value of the chapterTrackingEnabled property.
     * 
     */
    public boolean isChapterTrackingEnabled() {
        return chapterTrackingEnabled;
    }

    /**
     * Sets the value of the chapterTrackingEnabled property.
     * 
     */
    public void setChapterTrackingEnabled(boolean value) {
        this.chapterTrackingEnabled = value;
    }

    /**
     * Gets the value of the usingCustomVariables property.
     * 
     */
    public boolean isUsingCustomVariables() {
        return usingCustomVariables;
    }

    /**
     * Sets the value of the usingCustomVariables property.
     * 
     */
    public void setUsingCustomVariables(boolean value) {
        this.usingCustomVariables = value;
    }

    /**
     * Gets the value of the videoNameEvar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoNameEvar() {
        return videoNameEvar;
    }

    /**
     * Sets the value of the videoNameEvar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoNameEvar(String value) {
        this.videoNameEvar = value;
    }

    /**
     * Gets the value of the contentTypeEvar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentTypeEvar() {
        return contentTypeEvar;
    }

    /**
     * Sets the value of the contentTypeEvar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentTypeEvar(String value) {
        this.contentTypeEvar = value;
    }

    /**
     * Gets the value of the videoTimeEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoTimeEvent() {
        return videoTimeEvent;
    }

    /**
     * Sets the value of the videoTimeEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoTimeEvent(String value) {
        this.videoTimeEvent = value;
    }

    /**
     * Gets the value of the videoViewsEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoViewsEvent() {
        return videoViewsEvent;
    }

    /**
     * Sets the value of the videoViewsEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoViewsEvent(String value) {
        this.videoViewsEvent = value;
    }

    /**
     * Gets the value of the videoCompletesEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoCompletesEvent() {
        return videoCompletesEvent;
    }

    /**
     * Sets the value of the videoCompletesEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoCompletesEvent(String value) {
        this.videoCompletesEvent = value;
    }

}
